export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  REPORTER: 'reporter',
  WORKER: 'worker',
} as const;

// Exportamos como tipo para usarlo en interfaces de Usuario
export type Role = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  CREATE_USER: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  EDIT_USER: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DELETE_USER: [ROLES.SUPER_ADMIN],
  VIEW_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.REPORTER],
  MARK_ATTENDANCE: [ROLES.WORKER],
  VIEW_OWN_ATTENDANCE: [ROLES.WORKER],
  VIEW_ALL_ATTENDANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.REPORTER],
  EDIT_ATTENDANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_REPORTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.REPORTER],
  SEND_REPORTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
} as const;

export type Permission = keyof typeof PERMISSIONS;